# Breast Cancer - Visão geral do dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../dataset/Breast_Cancer.csv")

# Algumas colunas vêm com espaço sobrando no nome (ex: "T Stage ")
df.columns = df.columns.str.strip()

print(f"Linhas: {df.shape[0]} | Colunas: {df.shape[1]}")
df.head()

Linhas: 4024 | Colunas: 16

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive

## Tipos de dados e valores não nulos

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   str
 2   Marital Status          4024 non-null   str
 3   T Stage                 4024 non-null   str
 4   N Stage                 4024 non-null   str
 5   6th Stage               4024 non-null   str
 6   differentiate           4024 non-null   str
 7   Grade                   4024 non-null   str
 8   A Stage                 4024 non-null   str
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   str
 11  Progesterone Status     4024 non-null   str
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   str
dtypes: int64(5), str(11)
memory usage: 503.1 KB

## Valores ausentes e duplicados

In [3]:
print("Valores ausentes por coluna:")
print(df.isna().sum())
print(f"\nLinhas duplicadas: {df.duplicated().sum()}")

Valores ausentes por coluna:
Age                       0
Race                      0
Marital Status            0
T Stage                   0
N Stage                   0
6th Stage                 0
differentiate             0
Grade                     0
A Stage                   0
Tumor Size                0
Estrogen Status           0
Progesterone Status       0
Regional Node Examined    0
Reginol Node Positive     0
Survival Months           0
Status                    0
dtype: int64

Linhas duplicadas: 1

## Estatísticas das colunas numéricas

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,4024.0,53.972167,8.963134,30.0,47.0,54.0,61.0,69.0
Tumor Size,4024.0,30.473658,21.119696,1.0,16.0,25.0,38.0,140.0
Regional Node Examined,4024.0,14.357107,8.099675,1.0,9.0,14.0,19.0,61.0
Reginol Node Positive,4024.0,4.158052,5.109331,1.0,1.0,2.0,5.0,46.0
Survival Months,4024.0,71.297962,22.921430,1.0,56.0,73.0,90.0,107.0

In [5]:
df['Tumor Size']

0        4
1       35
2       63
3       18
4       41
        ..
4019     9
4020    46
4021    22
4022    44
4023    30
Name: Tumor Size, Length: 4024, dtype: int64